### ISSUE TITLE
Inventory and sorting

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/ProjectMP#17]
Time to do inventory and sorting!

```
client clicks on a slot
> gives packet ClickSlot to server
   > server processes, updates all the clients
   > changes will be reflected back on clients viewing
   > the client that clicked will get a packet to update their player's inventory
      > the server internally tracks the current cursor "slot" under the player inventory as an independent slot

```

**Comment by chrislo27** [comment]
Inventory will be one-person-at-a-time. That means only one person can access a chest at a time, and that client has full control over what they do. However this compromises hacking security, but I'm not worried about that just yet.

The actual logic is that a client may open a chest, sort as they wish, send it back to the server and the server will happily overwrite whatever contents with the new ones. The guard to sync issues is letting only one player access it at a time.

**Comment by matt-lebl** [comment]
Maybe a good compromise is to check the numbers on the items after the client sends back the inventories, and simply deny the action(s) if things don't add up.

**Comment by chrislo27** [comment]
Problem is that client handles their own inventories because a client enters a server with a character which has the inventory and all the other data on it, so either way the client can fudge up the results regardless. It can even not be the client; if a client picks up an item while in mid-sort it'll still count as wrong. The only real solution is to make the server fully authoritative, but I don't want to do that because I'm too lazy to.

**Comment by matt-lebl** [comment]
Gotcha. Maybe you could have the client hash their inventory and store it with the server, and do another hash check when the character enters again?

**Comment by chrislo27** [comment]
Then that will give a false positive if a client uses a character in another separate world and changes inventory.

The only solution is to make the server authoritative, which I'm not doing right this moment.

**Comment by matt-lebl** [comment]
:+1:

**Comment by chrislo27** [comment]
Gui work practically done (not tested but I'm confident enough); networking for onGuiClose needs to be done. HELP

**Comment by matt-lebl** [comment]
I'm shitty at... well everything, but I can give it my best shot if you really need something. :confused:

**Comment by chrislo27** [comment]
Giving your best shot doesn't involve being not contributive in a comment.

Your score is now: -2
_wiggles index finger in a way that's extremely condescending invokes you to feel sorry like that one thing that said "nuh-uh-uh, you didn't say the magic word"_

Joking aside, I need to figure out a system that will give inventory data from client to server and knowing what inventory is what. If inventories were only in blocks, this would be as easy as sending the block coordinates, but inventories can be in entities as well.

Come to think of it, I could structure it like the gui handler which creates a gui object from an id and coordinates.

EDIT: stupid mobile email formatting

**Comment by chrislo27** [comment]
Now that I know how to do everything, I'm going to switch it back to server-authoritative before it's too late. This will generally be easier to implement (maybe, I'm being pretty optimistic here) and if I need one-client-at-a-time implementation it won't be too hard to implement.

**Comment by chrislo27** [comment]
It's over... It's done...

I tried to optimize it a bit (maybe less item stack copying). So far it works with player inventory.
